targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            URL:
              type: String
            ISODateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: package:instagram_clone/graphql/scalars.dart
          clients:
            - graphql
