name: instagram_clone
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  # ferry: ^0.15.0+1
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.0
  drift: ^2.14.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0
  # flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  gql_http_link: ^1.0.1+1
  graphql: ^5.1.3
  icons_plus: ^5.0.0
  image: ^4.1.7
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  photo_gallery: ^2.1.1
  sqlite3_flutter_libs: ^0.5.18
  # graphql_flutter: ^5.2.0-beta.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  # ferry_generator: ^0.8.2
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  graphql_codegen: ^0.13.11
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/svg/"
    - "assets/svg/icons/"
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

flutter_gen:
  output: lib/core/gen/
